added msCrypto for IE11
andyperlitch/jsbn pull request #19
Opened 2017-05-03 13:23 UTC by mike-w-kelly

Changes tested locally with IE11 and open id connect (oidc.js)

2017-05-03 21:13 UTC, andyperlitch requested changes
A few comments on this. Also I see that vendor-prefix `msCrypto` has been removed as of IE11: https://msdn.microsoft.com/en-us/library/dn302339(v=vs.85).aspx

2017-05-03 21:13 UTC, andyperlitch commented on index.js
> +		  }
You'll need to fix the indentation here (there should only be a few lines changed here).

2017-05-03 21:13 UTC, andyperlitch commented on index.js
> +		if(typeof window !== "undefined" && crypto) {
It doesn't make sense to check for window being defined after the line you added which assumes it is there. You will need to set the `crypto` variable inside an if block like so:

```js
if (typeof window !== "undefined") {
   var crypto = window.crypto || window.msCrypto;
   if (crypto.getRandomValues) {
     // ...
```

2017-05-04 10:31 UTC, mike-w-kelly commented
The vendor prefix is still present in IE11. In fact if you try MS own examples with IE11 https://msdn.microsoft.com/en-us/library/dn302324(v=vs.85).aspx you'll get the error I reported. If you add in the window.msCrypto as per my pull request it works correctly. I'm making the changes you requested, will push up shortly.

2017-05-04 14:03 UTC, mike-w-kelly commented
Changes made and pushed up.

2020-05-18 11:26 UTC, joshxyzhimself commented
Hi, is this still a persistent issue for IE11?

2025-11-12 15:03 UTC, closed without merging